// <auto-generated />
using System;
using Appointments.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Appointments.Infrastructure.Migrations
{
    [DbContext(typeof(AppointmentContext))]
    [Migration("20240924103151_mig3")]
    partial class mig3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Appointments.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TcId")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("37016bfc-7b63-43f7-bdab-9ca13414669d"),
                            CreateDate = new DateTime(2000, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "boyr4z.m@gmail.com",
                            Name = "Muhammet",
                            Password = "boyraz46",
                            PhoneNumber = "05366765246",
                            Role = 1,
                            Surname = "Boyraz",
                            TcId = "25117914842"
                        },
                        new
                        {
                            Id = new Guid("484e9254-b804-422c-b4e7-5a2a5ef6cc8a"),
                            CreateDate = new DateTime(1998, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "serhatdnli@gmail.com",
                            Name = "Serhat",
                            Password = "serhat01",
                            PhoneNumber = "05353264771",
                            Role = 1,
                            Surname = "Denli",
                            TcId = "37458542624"
                        },
                        new
                        {
                            Id = new Guid("3f148351-615c-4d5c-a72a-e4618d7da31f"),
                            CreateDate = new DateTime(2000, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmetilhannm@gmail.com",
                            Name = "Ahmet",
                            Password = "ahmet65.",
                            PhoneNumber = "05432865247",
                            Role = 4,
                            Surname = "İlhan",
                            TcId = "18243593503"
                        },
                        new
                        {
                            Id = new Guid("710c4838-4b9f-4d17-9622-6b232830bbc9"),
                            CreateDate = new DateTime(1998, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "merter61m@gmail.com",
                            Name = "Gürkan",
                            Password = "merter61",
                            PhoneNumber = "05428564525",
                            Role = 2,
                            Surname = "Merter",
                            TcId = "27485393001"
                        },
                        new
                        {
                            Id = new Guid("36dfda88-1955-4702-8315-c231527be27b"),
                            CreateDate = new DateTime(2000, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dayanir34@gmail.com",
                            Name = "Talha",
                            Password = "dayanir34",
                            PhoneNumber = "05421452636",
                            Role = 5,
                            Surname = "Toğuşlu",
                            TcId = "28493040339"
                        },
                        new
                        {
                            Id = new Guid("6c62f73c-ecf6-45ff-b436-29109bda8fb2"),
                            CreateDate = new DateTime(1999, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "iboaydin34@gmail.com",
                            Name = "İbrahim",
                            Password = "iboaydin34",
                            PhoneNumber = "05424586954",
                            Role = 2,
                            Surname = "Aydın",
                            TcId = "38492039432"
                        },
                        new
                        {
                            Id = new Guid("69b7db5b-ddfb-4047-9d5f-68a4ebdf93e5"),
                            CreateDate = new DateTime(1995, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bakirr35@gmail.com",
                            Name = "Ali",
                            Password = "bakirr35",
                            PhoneNumber = "05489652542",
                            Role = 6,
                            Surname = "Bakır",
                            TcId = "78585458632"
                        },
                        new
                        {
                            Id = new Guid("48b11b33-029f-4354-96ef-a5565952de48"),
                            CreateDate = new DateTime(1998, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kayali06@gmail.com",
                            Name = "Ramazan",
                            Password = "kayali06",
                            PhoneNumber = "05471236549",
                            Role = 3,
                            Surname = "Kayalı",
                            TcId = "85458960214"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
