// <auto-generated />
using System;
using Appointments.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Appointments.Infrastructure.Migrations
{
    [DbContext(typeof(AppointmentContext))]
    partial class AppointmentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Appointments.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasAnnotation("Relational:JsonPropertyName", "createDate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "phoneNumber");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "role");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "surname");

                    b.Property<string>("TcId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasAnnotation("Relational:JsonPropertyName", "tcId");

                    b.HasKey("Id");

                    b.HasIndex("TcId")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0cedaf38-5989-460e-9c23-0dddec5bf745"),
                            CreateDate = new DateTime(2000, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "boyr4z.m@gmail.com",
                            Name = "Muhammet",
                            Password = "boyraz46",
                            PhoneNumber = "05366765246",
                            Role = 1,
                            Surname = "Boyraz",
                            TcId = "25117914842"
                        },
                        new
                        {
                            Id = new Guid("0ff0ae3a-5d72-4faf-a82b-2244ceda1070"),
                            CreateDate = new DateTime(1998, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "serhatdnli@gmail.com",
                            Name = "Serhat",
                            Password = "serhat01",
                            PhoneNumber = "05353264771",
                            Role = 1,
                            Surname = "Denli",
                            TcId = "37458542624"
                        },
                        new
                        {
                            Id = new Guid("b45636a6-65fc-4601-b06e-2bab59843427"),
                            CreateDate = new DateTime(2000, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmetilhannm@gmail.com",
                            Name = "Ahmet",
                            Password = "ahmet65.",
                            PhoneNumber = "05432865247",
                            Role = 4,
                            Surname = "İlhan",
                            TcId = "18243593503"
                        },
                        new
                        {
                            Id = new Guid("50141e01-7a2a-44d4-805e-f98e3023bc56"),
                            CreateDate = new DateTime(1998, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "merter61m@gmail.com",
                            Name = "Gürkan",
                            Password = "merter61",
                            PhoneNumber = "05428564525",
                            Role = 2,
                            Surname = "Merter",
                            TcId = "27485393001"
                        },
                        new
                        {
                            Id = new Guid("7628ca42-a08e-4965-b381-74e1986d2cfb"),
                            CreateDate = new DateTime(2000, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dayanir34@gmail.com",
                            Name = "Talha",
                            Password = "dayanir34",
                            PhoneNumber = "05421452636",
                            Role = 5,
                            Surname = "Toğuşlu",
                            TcId = "28493040339"
                        },
                        new
                        {
                            Id = new Guid("e517e81d-961e-495b-ad76-c5442a766fbe"),
                            CreateDate = new DateTime(1999, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "iboaydin34@gmail.com",
                            Name = "İbrahim",
                            Password = "iboaydin34",
                            PhoneNumber = "05424586954",
                            Role = 2,
                            Surname = "Aydın",
                            TcId = "38492039432"
                        },
                        new
                        {
                            Id = new Guid("3c5ebf4a-86c7-4003-aab3-bf10063cf1ea"),
                            CreateDate = new DateTime(1995, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bakirr35@gmail.com",
                            Name = "Ali",
                            Password = "bakirr35",
                            PhoneNumber = "05489652542",
                            Role = 6,
                            Surname = "Bakır",
                            TcId = "78585458632"
                        },
                        new
                        {
                            Id = new Guid("2352d459-c149-4ee7-a97b-bc5bf587d88d"),
                            CreateDate = new DateTime(1998, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kayali06@gmail.com",
                            Name = "Ramazan",
                            Password = "kayali06",
                            PhoneNumber = "05471236549",
                            Role = 3,
                            Surname = "Kayalı",
                            TcId = "85458960214"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
